image: mcr.microsoft.com/dotnet/sdk

stages:
    - build
    - test

before_script:
  - 'dotnet restore ChargingInfrastructurePlanning/ChargingInfrastructurePlanning.sln'

build:
    stage: build
    script:
        - "dotnet build ChargingInfrastructurePlanning/ChargingInfrastructurePlanning.sln"
    artifacts:
      paths:
        - bin/

test:
    stage: test
    script: 
        - ""
